@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZDBiYzFlNDk5Zjc0NGRmMGFmMTFkMCIsInVzZXJuYW1lIjoiZWRkeS5wZXJleiIsImlhdCI6MTYyNDI5OTA5NH0.UTdgVw6ZtV10ILdIQGmyN3fJs-B5DW6uMu90ACzBkio

### GET /api/blogs
GET http://localhost:3003/api/blogs/
Authorization: {{token}}

### POST /api/blogs
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: {{token}}

{
    "title":"Ejemplo 1",
    "author":"author",
    "url":"http://localhost.com/api/blogs",
    "likes":0
    
}
### DELETE /api/blogs/:id
DELETE http://localhost:3003/api/blogs/60d0e053f123b91d5c072c78
Authorization: {{token}}

### PUT /api/blogs/:id
PUT http://localhost:3003/api/blogs/60cbbb1cff87301424602b18
Content-Type: application/json
Authorization: {{token}}

{
    "title":"Ejemplo 3",
    "author":"author 3",
    "url":"http://localhost.com/api/blogs/2",
    "likes":12
}


