
### GET /api/blogs
GET http://localhost:3003/api/blogs/

### POST /api/blogs
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title":"Ejemplo 1",
    "author":"author",
    "url":"http://localhost.com/api/blogs",
    "likes":0
}
### DELETE /api/blogs/:id
DELETE http://localhost:3003/api/blogs/60c8c652064a390b54a325e0

### PUT /api/blogs/:id
PUT http://localhost:3003/api/blogs/60c8b70b6053913e287dd9f8
Content-Type: application/json

{
    "title":"Ejemplo 3",
    "author":"author 3",
    "url":"http://localhost.com/api/blogs/2",
    "likes":12
}


