### POST /api/users/
POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "name":"midudev",
    "username":"midudev",
    "password":"123"
}

### GET /api/users/
GET http://localhost:3003/api/users/
